import fs from "node:fs";
import path from "node:path";

const dir = path.join(process.cwd(), "src", "data", "mealdb");

const ingredientDict = {
  "chicken breast": "tavuk göğsü",
  "chicken thighs": "tavuk but",
  "chicken": "tavuk",
  "beef": "dana eti",
  "lamb": "kuzu eti",
  "pork": "domuz eti",
  "goat": "keçi eti",
  "fish": "balık",
  "salmon": "somon",
  "tuna": "ton balığı",
  "shrimp": "karides",
  "prawn": "karides",
  "crab": "yengeç",
  "lobster": "ıstakoz",
  "mussel": "midye",
  "clam": "istiridye",
  "oyster": "istiridye",
  "squid": "kalamar",
  "octopus": "ahtapot",
  "onion": "soğan",
  "garlic": "sarımsak",
  "tomato": "domates",
  "potato": "patates",
  "carrot": "havuç",
  "pepper": "biber",
  "red pepper": "kırmızı biber",
  "green pepper": "yeşil biber",
  "chilli": "acı biber",
  "chili": "acı biber",
  "cucumber": "salatalık",
  "lettuce": "marul",
  "cabbage": "lahana",
  "spinach": "ıspanak",
  "kale": "kara lahana",
  "broccoli": "brokoli",
  "cauliflower": "karnabahar",
  "zucchini": "kabak",
  "eggplant": "patlıcan",
  "mushroom": "mantar",
  "oyster mushroom": "istiridye mantarı",
  "button mushroom": "beyaz mantar",
  "portobello": "portobello mantarı",
  "shiitake": "shiitake mantarı",
  "leek": "pırasa",
  "shallot": "shallot",
  "spring onion": "soğan",
  "celery": "kereviz",
  "parsley": "maydanoz",
  "dill": "dereotu",
  "mint": "nane",
  "basil": "fesleğen",
  "oregano": "kekik",
  "thyme": "kekik",
  "rosemary": "biberiye",
  "sage": "adaçayı",
  "coriander": "kişniş",
  "cumin": "kimyon",
  "turmeric": "zerdeçal",
  "ginger": "zencefil",
  "cinnamon": "tarçın",
  "clove": "karanfil",
  "nutmeg": "muskat",
  "cardamom": "kakule",
  "saffron": "safran",
  "bay leaf": "defne yaprağı",
  "black pepper": "karabiber",
  "salt": "tuz",
  "sugar": "şeker",
  "honey": "bal",
  "olive oil": "zeytinyağı",
  "vegetable oil": "bitkisel yağ",
  "butter": "tereyağı",
  "milk": "süt",
  "cream": "kaymak",
  "sour cream": "ekşi krema",
  "yogurt": "yoğurt",
  "cheese": "peynir",
  "feta": "feta peyniri",
  "parmesan": "parmesan",
  "mozzarella": "mozzarella",
  "halloumi": "hellim",
  "cheddar": "cheddar",
  "egg": "yumurta",
  "flour": "un",
  "rice": "pirinç",
  "pasta": "makarna",
  "spaghetti": "spagetti",
  "penne": "penne",
  "lasagne": "lasanya",
  "noodle": "erişte",
  "bread": "ekmek",
  "bun": "ekmek",
  "tortilla": "tortilla",
  "lentil": "mercimek",
  "chickpea": "nohut",
  "bean": "fasulye",
  "black bean": "siyah fasulye",
  "white bean": "beyaz fasulye",
  "kidney bean": "kırmızı fasulye",
  "pea": "bezelye",
  "corn": "mısır",
  "quinoa": "quinoa",
  "couscous": "kuskus",
  "barley": "arpa",
  "oat": "yulaf",
  "walnut": "ceviz",
  "almond": "badem",
  "pistachio": "fıstık",
  "hazelnut": "fındık",
  "peanut": "fıstık",
  "cashew": "kaju",
  "sesame": "susam",
  "sunflower seed": "ayçekirdeği",
  "pumpkin seed": "kabak çekirdeği",
  "flax": "keten",
  "coconut": "hindistan cevizi",
  "coconut milk": "hindistan cevizi sütü",
  "raisin": "kuru üzüm",
  "date": "hurma",
  "fig": "incir",
  "apricot": "kayısı",
  "prune": "kuru erik",
  "lemon": "limon",
  "lime": "misket limonu",
  "orange": "portakal",
  "apple": "elma",
  "pear": "armut",
  "banana": "muz",
  "strawberry": "çilek",
  "blueberry": "yaban mersini",
  "raspberry": "ahududu",
  "blackberry": "böğürtlen",
  "grape": "üzüm",
  "melon": "kavun",
  "watermelon": "karpuz",
  "peach": "şeftali",
  "plum": "erik",
  "cherry": "kiraz",
  "pomegranate": "nar",
  "pineapple": "ananas",
  "mango": "mango",
  "avocado": "avokado",
  "artichoke": "enginar",
  "asparagus": "kuşkonmaz",
  "green bean": "taze fasulye",
  "snow pea": "bezelye",
  "sweet potato": "tatlı patates",
  "pumpkin": "bal kabağı",
  "butternut squash": "balkabağı",
  "spaghetti squash": "spagetti kabak",
  "bean sprout": "fasulye filizi",
  "bamboo shoot": "bambu filizi",
  "water chestnut": "su kestanesi",
  "lotus root": "nilüfer kökü",
  "tofu": "tofu",
  "tempeh": "tempe",
  "seitan": "seitan",
  "soy sauce": "soya sosu",
  "fish sauce": "balık sosu",
  "oyster sauce": "istiridye sosu",
  "hoisin sauce": "hoisin sosu",
  "sweet chilli sauce": "tatlı acı sos",
  "hot sauce": "acı sos",
  "chilli sauce": "acı sos",
  "hotsauce": "acı sos",
  "tomato sauce": "domates sosu",
  "tomato paste": "salça",
  "ketchup": "ketçap",
  "mustard": "hardal",
  "mayonnaise": "mayonez",
  "vinegar": "sirke",
  "lemon juice": "limon suyu",
  "lime juice": "limon suyu",
  "wine": "şarap",
  "red wine": "kırmızı şarap",
  "white wine": "beyaz şarap",
  "beer": "bira",
  "stock": "et suyu",
  "chicken stock": "tavuk suyu",
  "beef stock": "dana suyu",
  "vegetable stock": "sebze suyu",
  "fish stock": "balık suyu",
  "water": "su",
  "ice": "buz",
  "oil": "yağ",
  "tablespoon": "yemek kaşığı",
  "teaspoon": "çay kaşığı",
  "cup": "su bardağı",
  "grams": "gram",
  "kilograms": "kilogram",
  "ounce": "ons",
  "pound": "pound",
  "lb": "pound",
  "oz": "ons",
  "ml": "mililitre",
  "l": "litre",
  "pinch": "tutam",
  "dash": "tutam",
  "handful": "avuç",
  "bunch": "demet",
  "sprigs": "dallar",
  "sprig": "dal",
  "leaves": "yapraklar",
  "leaf": "yaprak",
  "can": "konserve",
  "tin": "konserve",
  "packet": "paket",
  "sachet": "poşet",
  "block": "blok",
  "bar": "bar",
  "roll": "rulo",
  "slice": "dilim",
  "slices": "dilimler",
  "piece": "parça",
  "pieces": "parçalar",
  "whole": "bütün",
  "half": "yarım",
  "quarter": "çeyrek",
  "chopped": "doğranmış",
  "sliced": "dilimlenmiş",
  "diced": "küp doğranmış",
  "minced": "kıyılmış",
  "crushed": "ezilmiş",
  "grated": "rendelenmiş",
  "peeled": "soyulmuş",
  "cooked": "pişmiş",
  "raw": "çiğ",
  "fresh": "taze",
  "dried": "kuru",
  "frozen": "dondurulmuş",
  "canned": "konserve",
  "ground": "çekilmiş",
  "roasted": "kavrulmuş",
  "toasted": "kızartılmış",
  "fried": "kızartılmış",
  "boiled": "haşlanmış",
  "steamed": "buharda pişmiş",
  "grilled": "ızgarada pişmiş",
  "baked": "fırında pişmiş",
  "sauteed": "kavrulmuş",
  "braised": "kısık ateşte pişmiş",
  "marinated": "marine edilmiş",
  "seasoned": "baharatlanmış",
  "taste": "tat",
  "medium": "orta",
  "large": "büyük",
  "small": "küçük",
  "fine": "ince",
  "coarse": "kaba",
  "thin": "ince",
  "thick": "kalın",
  "tender": "yumuşak",
  "firm": "sert",
  "soft": "yumuşak",
  "ripe": "olgun",
  "unripe": "ham",
  "sweet": "tatlı",
  "sour": "ekşi",
  "bitter": "acı",
  "spicy": "baharatlı",
  "mild": "hafif",
  "hot": "sıcak",
  "warm": "ılık",
  "cold": "soğuk",
  "heat": "ısı",
  "fire": "ateş",
  "pan": "tava",
  "pot": "tencere",
  "oven": "fırın",
  "stove": "ocak",
  "grill": "ızgara",
  "barbecue": "mangal",
  "air fryer": "hava fritözü",
  "pressure cooker": "düdüklü tencere",
  "slow cooker": "yavaş pişirici",
  "blender": "blender",
  "mixer": "mikser",
  "whisk": "çırpıcı",
  "spatula": "spatula",
  "knife": "bıçak",
  "cutting board": "kesme tahtası",
  "bowl": "kase",
  "plate": "tabak",
  "serving": "porsiyon",
  "serve": "servis et",
  "garnish": "süsle",
  "topping": "üzerine",
  "side": "yan",
  "salad": "salata",
  "soup": "çorba",
  "sauce": "sos",
  "dip": "dip",
  "spread": "sürülebilir",
  "dressing": "sos",
  "marinade": "marinade",
  "rub": "baharat karışımı",
  "batter": "hamur",
  "dough": "hamur",
  "crust": "kabuk",
  "filling": "iç malzeme",
  "base": "taban",
  "layer": "kat",
  "top": "üst",
  "bottom": "alt",
  "diagonal": "çapraz",
  "lengthwise": "boydan",
  "crosswise": "enine",
  "diameter": "çap",
  "height": "yükseklik",
  "depth": "derinlik",
  "volume": "hacim",
  "weight": "ağırlık",
  "temperature": "sıcaklık",
  "time": "zaman",
  "minute": "dakika",
  "minutes": "dakika",
  "hour": "saat",
  "hours": "saat",
  "day": "gün",
  "days": "gün",
  "week": "hafta",
  "month": "ay",
  "year": "yıl",
  "instant": "anında",
  "overnight": "bir gece",
  "ahead": "önceden",
  "before": "önce",
  "after": "sonra",
  "during": "sırasında",
  "while": "-iken",
  "until": "-e kadar",
  "about": "yaklaşık",
  "approximately": "yaklaşık",
  "exactly": "tam",
  "more": "daha fazla",
  "less": "daha az",
  "most": "en çok",
  "least": "en az",
  "all": "tümü",
  "some": "biraz",
  "many": "çok",
  "few": "az",
  "several": "birkaç",
  "enough": "yeterli",
  "extra": "fazladan",
  "additional": "ek",
  "optional": "isteğe bağlı",
  "required": "gerekli",
  "necessary": "gerekli",
  "available": "mevcut",
  "leftover": "artık",
  "remaining": "kalan",
  "rest": "dinlen",
  "stir": "karıştır",
  "mix": "karıştır",
  "combine": "birleştir",
  "fold": "kat",
  "whisk": "çırp",
  "beat": "çırp",
  "blend": "karıştır",
  "puree": "püre",
  "process": "işle",
  "grind": "çek",
  "crush": "ez",
  "squeeze": "sık",
  "drain": "süz",
  "rinse": "çıkar",
  "wash": "yıka",
  "peel": "soy",
  "cut": "kes",
  "slice": "dilimle",
  "dice": "küp doğra",
  "chop": "doğra",
  "mince": "kıy",
  "grate": "rendele",
  "zest": "kabuğunu rendele",
  "juice": "suyunu sık",
  "measure": "ölç",
  "weigh": "tart",
  "prepare": "hazırla",
  "preheat": "ısıt",
  "heat": "ısıt",
  "warm": "ısıt",
  "cool": "soğut",
  "chill": "soğut",
  "freeze": "dondur",
  "thaw": "erit",
  "cook": "pişir",
  "fry": "kızart",
  "saute": "kavur",
  "sear": "mühürle",
  "brown": "kızart",
  "roast": "kavur",
  "bake": "pişir",
  "grill": "ızgarada pişir",
  "broil": "ızgara",
  "steam": "buharla pişir",
  "boil": "kaynat",
  "simmer": "kaynat",
  "poach": "sudak",
  "stew": "yahnile",
  "braise": "kısık ateşte pişir",
  "season": "baharatla",
  "adjust": "ayarla",
  "add": "ekle",
  "remove": "çıkar",
  "cover": "kapat",
  "uncover": "aç",
  "reduce": "kıs",
  "increase": "artır",
  "shake": "çalkala",
  "toss": "karıştır",
  "sprinkle": "serp",
  "drizzle": "gezdir",
  "pour": "dök",
  "spoon": "kaşıkla al",
  "transfer": "aktar",
  "place": "yerleştir",
  "arrange": "düzenle",
  "fill": "doldur",
  "wrap": "sar",
  "tie": "bağla",
  "skewer": "şişe takar",
  "insert": "yerleştir",
  "press": "bastır",
  "flatten": "düzleştir",
  "roll out": "aç",
  "knead": "yoğur",
  "rise": "mayalandır",
  "proof": "mayalandır",
  "punch down": "yoğur",
  "shape": "şekil ver",
  "form": "şekil ver",
  "mold": "kalıba dök",
  "line": "yerleştir",
  "grease": "yağla",
  "brush": "fırçala",
  "spread": "sür",
  "repeat": "tekrarla",
  "continue": "devam et",
  "finish": "bitir",
  "complete": "tamamla",
  "ready": "hazır",
  "done": "bitti",
  "enjoy": "afiyet olsun",
  "decorate": "süsle",
  "present": "sun",
  "portion": "porsiyonla",
  "divide": "böl",
  "share": "paylaş",
  "eat": "ye",
  "drink": "iç",
  "smell": "kokla",
  "touch": "dokun",
  "feel": "hisset",
  "see": "gör",
  "look": "bak",
  "check": "kontrol et",
  "make sure": "emin ol",
  "ensure": "sağla",
  "try": "dene",
  "attempt": "denemek",
  "practice": "pratik",
  "learn": "öğren",
  "teach": "öğret",
  "show": "göster",
  "explain": "açıkla",
  "describe": "tarif et",
  "list": "listele",
  "note": "not et",
  "remember": "hatırla",
  "forget": "unut",
  "think": "düşün",
  "know": "bil",
  "understand": "anla",
  "believe": "inan",
  "hope": "um",
  "want": "ist",
  "need": "gerek",
  "like": "hoşlan",
  "love": "sev",
  "hate": "nefret et",
  "prefer": "tercih et",
  "choose": "seç",
  "pick": "seç",
  "select": "seç",
  "decide": "karar ver",
  "plan": "planla",
  "organize": "düzenle",
  "arrange": "ayarla",
  "clean": "temizle",
  "dry": "kurut",
  "wet": "ıslat",
  "soak": "ıslat",
  "strain": "süz",
  "filter": "süz",
  "sift": "ele",
  "sort": "ayık",
  "separate": "ayır",
  "join": "birleştir",
  "connect": "bağla",
  "attach": "tak",
  "detach": "çıkar",
  "strip": "soy",
  "shred": "rendele",
  "tear": "yırt",
  "break": "kır",
  "smash": "ez",
  "mash": "ez",
  "liquefy": "sıvılaştır",
  "solidify": "katılaştır",
  "melt": "erit",
  "dissolve": "çöz",
  "evaporate": "buharlaştır",
  "condense": "yoğunlaştır",
  "concentrate": "yoğunlaştır",
  "dilute": "seyrelt",
  "sort": "sırala",
  "clean up": "temizle",
  "pick up": "al",
  "put down": "koy",
  "put away": "kaldır",
  "take out": "çıkar",
  "throw at": "at",
  "get rid of": "kurtul",
  "dispose of": "at",
  "recycle": "geri dönüştür",
  "reuse": "tekrar kullan",
  "reduce": "azalt",
  "compost": " gübre",
  "landfill": "çöplük",
  "dump": "dök",
  "pour into": "dök",
  "fill up": "doldur",
  "empty": "boşalt",
  "load": "yükle",
  "unload": "boşalt",
  "pack": "paketle",
  "unpack": "aç",
  "wrap up": "sar",
  "unwrap": "aç",
  "cover up": "ört",
  "uncover": "aç",
  "hide": "gizle",
  "seek": "ara",
  "find out": "bul",
  "discover": "keşfet",
  "invent": "icat et",
  "create": "yarat",
  "design": "tasarla",
  "plan": "planla",
  "imagine": "hayal et",
  "dream": "rüya görmek",
  "wish": "dilek",
  "hope for": "umut et",
  "wait for": "bekle",
  "look for": "ara",
  "search for": "ara",
  "hunt for": "avla",
  "track": "takip et",
  "trace": "iz sürmek",
  "follow": "takip et",
  "chase": "kovalamak",
  "pursue": "takip et",
  "catch": "yakalamak",
  "capture": "yakalamak",
  "trap": "tuzağa düşür",
  "snare": "kıskaç",
  "net": "ağ",
  "hook": "kanca",
  "line": "olta",
  "sinker": "ağırlık",
  "bait": "yem",
  "lure": "yem",
  "decoy": "yem",
  "bait and switch": "aldatmaca",
  "trick": "hile",
  "trap": "tuzak",
  "deception": "aldatmaca",
  "fraud": "dolandırıcılık",
  "scam": "dolandırıcılık",
  "con": "kumar",
  "cheat": "hile",
  "deceive": "aldat",
  "mislead": "yanılt",
  "confuse": "karıştır",
  "puzzte": "şaşırt",
  "amuse": "eğlendir",
  "entertain": "eğlendir",
  "delight": "keyif al",
  "tickle": "gıdıkla",
  "joke": "şaka",
  "laugh": "gülmek",
  "cry": "ağlamak",
  "sob": "hıçkırmak",
  "weep": "ağlamak",
  "wail": "inlemek",
  "moan": "inlemek",
  "groan": "inlemek",
  "sigh": "iç çek",
  "gasp": "nefes nefese",
  "pant": "nefes nefese",
  "wheeze": "hırıltı",
  "cough": "öksür",
  "sneeze": "hapşır",
  "sniff": "kokla",
  "snort": "homurdan",
  "grunt": "homurdan",
  "moan": "inle",
  "scream": "çığlık at",
  "shriek": "çığlık",
  "yell": "bağırmak",
  "shout": "bağırmak",
  "cry out": "haykır",
  "call out": "seslen",
  "whisper": "fısılda",
  "mumble": "mırıldan",
  "mutter": "mırıldan",
  "stutter": "kekelemek",
  "stammer": "kekelemek",
  "babble": "saçmalamak",
  "ramble": "saçmalamak",
  "chatter": "çene çalmak",
  "gossip": "dedikodu yap",
  "chat": "sohbet et",
  "talk": "konuş",
  "speak": "konuş",
  "say": "söyle",
  "tell": "anlat",
  "ask": "sor",
  "answer": "cevap ver",
  "respond": "cevap ver",
  "reply": "cevap ver",
  "state": "belirt",
  "declare": "beyan et",
  "announce": "duyur",
  "proclaim": "ilan et",
  "claim": "iddia et",
  "assert": "iddia et",
  "affirm": "onayla",
  "confirm": "onayla",
  "verify": "doğrula",
  "validate": "doğrula",
  "prove": "kanıtla",
  "show": "göster",
  "demonstrate": "göster",
  "illustrate": "örnek göster",
  "exemplify": "örnek",
  "embody": "somutlaştır",
  "personify": "kişileştir",
  "typify": "temsil et",
  "characterize": "karakterize",
  "distinguish": "ayırt et",
  "differentiate": "farklılaştır",
  "discriminate": "ayrım yap",
  "segregate": "ayır",
  "isolate": "izole et",
  "insulate": "yalıt",
  "quarantine": "karantina",
  "seclude": "gerçek",
  "exclude": "dışla",
  "eliminate": "elemek",
  "eradicate": "kökünü kurut",
  "extinguish": "söndür",
  "extirpate": "kökünü kurut",
  "exterminate": "yok et",
  "annihilate": "yok et",
  "obliterate": "yok et",
  "erase": "sil",
  "delete": "sil",
  "cancel": "iptal et",
  "void": "geçersiz",
  "nullify": "geçersiz kıl",
  "invalidate": "geçersiz kıl",
  "revoke": "iptal et",
  "rescind": "iptal et",
  "repeal": "kaldır",
  "abolish": "kaldır",
  "terminate": "sonlandır",
  "end": "bitir",
  "finish": "bitir",
  "complete": "tamamla",
  "conclude": "sonuçlandır",
  "close": "kapat",
  "shut": "kapat",
  "lock": "kilitle",
  "unlock": "kilidi aç",
  "bolt": "sürgüle",
  "latch": "mandalı tak",
  "fasten": "bağla",
  "unfasten": "çöz",
  "tie up": "bağla",
  "untie": "çöz",
  "loosen": "gevşet",
  "tighten": "sık",
  "tension": "gerginlik",
  "stress": "stres",
  "strain": "gerginlik",
  "pressure": "baskı",
  "force": "zorla",
  "compel": "zorunlu kıl",
  "oblige": "zorunlu kıl",
  "coerce": "zorla",
  "pressure": "baskı yap",
  "push": "it",
  "pull": "çek",
  "drag": "sürükle",
  "draw": "çek",
  "haul": "çek",
  "heave": "kaldır",
  "lift": "kaldır",
  "raise": "yükselt",
  "elevate": "yükselt",
  "hoist": "kaldır",
  "boost": "artır",
  "elevate": "yükselt",
  "promote": "terfi et",
  "advance": "ilerlet",
  "further": "ilerlet",
  "encourage": "teşvik et",
  "support": "destekle",
  "back": "destekle",
  "endorse": "onayla",
  "approve": "onayla",
  "sanction": "onayla",
  "ratify": "onayla",
  "authorize": "yetki ver",
  "empower": "yetki ver",
  "enable": "olanak tanı",
  "allow": "izin ver",
  "permit": "izin ver",
  "let": "izin ver",
  "grant": "bağışla",
  "give": "ver",
  "provide": "sağla",
  "supply": "sağla",
  "furniture": "sağla",
  "equip": "donat",
  "arm": "silahlandır",
  "prepare": "hazırla",
  "ready": "hazırla",
  "set up": "kur",
  "establish": "kur",
  "found": "kur",
  "institute": "kur",
  "organize": "düzenle",
  "arrange": "düzenle",
  "order": "düzenle",
  "systematize": "sistematikleştir",
  "methodize": "yöntemleştir",
  "rationalize": "mantıklılaştır",
  "streamline": "sadeleştir",
  "simplify": "basitleştir",
  "facilitate": "kolaylaştır",
  "ease": "kolaylaştır",
  "comfort": "rahatlat",
  "soothe": "yatıştır",
  "calm": "sakinleştir",
  "pacify": "yatıştır",
  "appease": "yatıştır",
  "mollify": "yatıştır",
  "placate": "yatıştır",
  "conciliate": "uzlaştır",
  "reconcile": "uzlaştır",
  "mediate": "arabuluculuk et",
  "arbitrate": "hakemlik et",
  "negotiate": "müzakere et",
  "bargain": "pazarlık yap",
  "haggle": "pazarlık yap",
  "dicker": "pazarlık yap",
  "barter": "takas et",
  "trade": "takas et",
  "exchange": "değiştir",
  "swap": "takas et",
  "switch": "değiştir",
  "substitute": "yerine koy",
  "replace": "değiştir",
  "displace": "yerini değiştir",
  "supersede": "yerini al",
  "supplant": "yerini al",
  "outdo": "geç",
  "surpass": "aş",
  "exceed": "aş",
  "transcend": "aş",
  "overcome": "aş",
  "conquer": "fethet",
  "defeat": "yen",
  "beat": "yen",
  "overpower": "alt et",
  "overwhelm": "boğ",
  "overwhelm": "bunalt",
  "engulf": "yut",
  "swallow": "yut",
  "devour": "yut",
  "consume": "tüket",
  "eat up": "ye bitir",
  "drink up": "iç bitir",
  "finish off": "bitir",
  "complete": "tamamla",
  "use up": "tüket",
  "deplete": "tüket",
  "exhaust": "tüket",
  "drain": "tüket",
  "empty": "boşalt",
  "run out": "tüken",
  "short": "kısa",
  "scarce": "kıt",
  "rare": "nadir",
  "limited": "sınırlı",
  "restricted": "sınırlı",
  "confined": "sınırlı",
  "bounded": "sınırlı",
  "finite": "sonlu",
  "infinite": "sonsuz",
  "eternal": "sonsuz",
  "everlasting": "sonsuz",
  "perpetual": "sürekli",
  "permanent": "kalıcı",
  "temporary": "geçici",
  "provisional": "geçici",
  "tentative": "geçici",
  "momentary": "anlık",
  "fleeting": "geçici",
  "transient": "geçici",
  "transitory": "geçici",
  "ephemeral": "geçici",
  "short-lived": "kısa ömürlü",
  "brief": "kısa",
  "quick": "hızlı",
  "rapid": "hızlı",
  "swift": "hızlı",
  "speedy": "hızlı",
  "fast": "hızlı",
  "slow": "yavaş",
  "sluggish": "yavaş",
  "lethargic": "yavaş",
  "languid": "yavaş",
  "listless": "yavaş",
  "inactive": "hareketsiz",
  "idle": "boş",
  "inert": "hareketsiz",
  "passive": "pasif",
  "static": "sabit",
  "stationary": "sabit",
  "fixed": "sabit",
  "immobile": "hareketsiz",
  "motionless": "hareketsiz",
  "still": "sabit",
  "quiet": "sessiz",
  "silent": "sessiz",
  "noisy": "gürültülü",
  "loud": "yüksek sesli",
  "deafening": "kulak tırabilecek",
  "earsplitting": "kulak tırabilecek",
  "thunderous": "gök gürültüsü",
  "booming": "yankılanan",
  "resounding": "çınlayan",
  "ringing": "çınlayan",
  "tinkling": "çınlayan",
  "jingling": "çınlayan",
  "clinking": "çınlayan",
  "clanking": "gürültülü",
  "rattling": "şıngırdayan",
  "clattering": "şıngırdayan",
  "crashing": "gürültülü",
  "smashing": "gürültülü",
  "banging": "gürültülü",
  "thumping": "gürültülü",
  "thudding": "gürültülü",
  "pounding": "gürültülü",
  "hammering": "gürültülü",
  "drumming": "davul çalma",
  "beating": "vurma",
  "pulsing": "nabız",
  "throbbing": "nabız",
  "pounding": "vurma",
  "pulsation": "nabız",
  "heartbeat": "kalp atışı",
  "pulse": "nabız",
  "rhythm": "ritim",
  "beat": "vuruş",
  "tempo": "tempo",
  "pace": "adım",
  "cadence": "ritim",
  "meter": "metre",
  "rhyme": "kafiye",
  "verse": "kafiye",
  "stanza": "kafiye",
  "line": "satır",
  "word": "kelime",
  "syllable": "hece",
  "letter": "harf",
  "character": "karakter",
  "symbol": "sembol",
  "sign": "işaret",
  "mark": "işaret",
  "signal": "sinyal",
  "indication": "gösterge",
  "evidence": "kanıt",
  "proof": "kanıt",
  "verification": "doğrulama",
  "confirmation": "onay",
  "authentication": "kimlik doğrulama",
  "validation": "doğrulama",
  "certification": "sertifika",
  "accreditation": "akreditasyon",
  "approval": "onay",
  "endorsement": "onay",
  "sanction": "onay",
  "authorization": "yetki",
  "permission": "izin",
  "consent": "rizası",
  "assent": "onay",
  "approbation": "onay",
  "ratification": "onay",
  "confirmation": "onay",
  "validation": "onay",
  "verification": "doğrulama",
  "substantiation": "doğrulama",
  "corroboration": "teyit",
  "attestation": "tanıklık",
  "witness": "tanık",
  "testimony": "tanıklık",
  "deposition": "ifade",
  "statement": "beyan",
  "declaration": "beyan",
  "proclamation": "ilan",
  "announcement": "duyuru",
  "notice": "bildirim",
  "notification": "bildirim",
  "warning": "uyarı",
  "caution": "uyarı",
  "alert": "uyarı",
  "alarm": "alarm",
  "signal": "sinyal",
  "indication": "gösterge",
  "symptom": "belirti",
  "sign": "belirti",
  "indication": "gösterge",
  "evidence": "delil",
  "proof": "kanıt",
  "demonstration": "gösteri",
  "display": "gösteri",
  "exhibition": "sergi",
  "show": "gösteri",
  "performance": "performans",
  "act": "eylem",
  "action": "eylem",
  "deed": "eylem",
  "feat": "başarı",
  "achievement": "başarı",
  "accomplishment": "başarı",
  "success": "başarı",
  "failure": "başarısızlık",
  "disaster": "felaket",
  "catastrophe": "felaket",
  "calamity": "felaket",
  "tragedy": "trajedi",
  "misfortune": "talihsizlik",
  "bad luck": "şanssızlık",
  "good luck": "iyi şans",
  "fortune": "kısmet",
  "destiny": "kader",
  "fate": "kader",
  "doom": "kader",
  "lot": "kader",
  "portion": "nasip",
  "share": "pay",
  "part": "parça",
  "piece": "parça",
  "bit": "parça",
  "fragment": "parça",
  "shard": "parça",
  "sliver": "parça",
  "chip": "parça",
  "chunk": "parça",
  "hunk": "parça",
  "lump": "parça",
  "block": "blok",
  "brick": "tuğla",
  "stone": "taş",
  "rock": "taş",
  "pebble": "çakıl",
  "gravel": "çakıl",
  "sand": "kum",
  "dust": "toz",
  "dirt": "kir",
  "soil": "toprak",
  "earth": "toprak",
  "ground": "zemin",
  "land": "arazi",
  "territory": "bölge",
  "region": "bölge",
  "area": "alan",
  "zone": "bölge",
  "district": "bölge",
  "neighborhood": "mahalle",
  "quarter": "semt",
  "sector": "sektör",
  "section": "bölüm",
  "division": "bölüm",
  "department": "bölüm",
  "branch": "şube",
  "wing": "kanat",
  "arm": "kol",
  "leg": "bacak",
  "foot": "ayak",
  "hand": "el",
  "finger": "parmak",
  "thumb": "başparmak",
  "wrist": "bilek",
  "elbow": "dirsek",
  "shoulder": "omuz",
  "chest": "göğüs",
  "back": "sırt",
  "waist": "bel",
  "hip": "kalça",
  "knee": "diz",
  "ankle": "ayak bileği",
  "heel": "topuk",
  "toe": "ayak parmağı",
  "head": "baş",
  "face": "yüz",
  "eye": "göz",
  "ear": "kulak",
  "nose": "burun",
  "mouth": "ağız",
  "lip": "dudak",
  "tongue": "dil",
  "tooth": "diş",
  "gum": "diş eti",
  "neck": "boyun",
  "throat": "boğaz",
  "chin": "çene",
  "cheek": "yanak",
  "forehead": "alın",
  "eyebrow": "kaş",
  "eyelash": "kirpik",
  "hair": "saç",
  "beard": "sakal",
  "mustache": "bıyık",
  "whisker": "bıyık",
  "flesh": "et",
  "bone": "kemik",
  "skin": "deri",
  "nail": "tırnak",
  "knuckle": "parmak ucu",
  "palm": "avuç",
  "fist": "yumruk",
  "thumb": "başparmak",
  "index finger": "işaret parmağı",
  "middle finger": "orta parmak",
  "ring finger": "yüzük parmağı",
  "little finger": "serçe parmak",
  "right": "sağ",
  "left": "sol",
  "up": "yukarı",
  "down": "aşağı",
  "forward": "ileri",
  "backward": "geri",
  "inward": "içe",
  "outward": "dışa",
  "inward": "içe",
  "outward": "dışa",
  "upward": "yukarı",
  "downward": "aşağı",
  "leftward": "sola",
  "rightward": "sağa",
  "north": "kuzey",
  "south": "güney",
  "east": "doğu",
  "west": "batı",
  "northeast": "kuzeydoğu",
  "northwest": "kuzeybatı",
  "southeast": "güneydoğu",
  "southwest": "güneybatı",
};

const stepPatterns = [
  [/^STEP \d+$/i, (m) => `ADIM ${m[0].split(" ")[1]}`],
  [/preheat the oven to (\d+)C/i, (_, temp) => `Fırını ${temp} dereceye ısıtın`],
  [/preheat the oven to (\d+)°C/i, (_, temp) => `Fırını ${temp} dereceye ısıtın`],
  [/fry for (\d+)-(\d+) mins?/i, (_, min1, min2) => `${min1}-${min2} dakika kızartın`],
  [/cook for (\d+) mins?/i, (_, min) => `${min} dakika pişirin`],
  [/bake for (\d+) mins?/i, (_, min) => `${min} dakika fırında pişirin`],
  [/simmer for (\d+) mins?/i, (_, min) => `${min} dakika kaynatın`],
  [/season with/i, () => `baharatlayın`],
  [/add/i, () => `ekleyin`],
  [/stir/i, () => `karıştırın`],
  [/mix/i, () => `karıştırın`],
  [/combine/i, () => `birleştirin`],
  [/pour/i, () => `dökün`],
  [/place/i, () => `yerleştirin`],
  [/top/i, () => `üzerine koyun`],
  [/serve/i, () => `servis edin`],
  [/garnish/i, () => `süsleyin`],
  [/drizzle/i, () => `gezdirin`],
  [/sprinkle/i, () => `serpin`],
  [/toss/i, () => `karıştırın`],
  [/heat/i, () => `ısıtın`],
  [/reduce/i, () => `kısın`],
  [/increase/i, () => `artırın`],
  [/cover/i, () => `kapatın`],
  [/uncover/i, () => `açın`],
  [/remove/i, () => `çıkarın`],
  [/transfer/i, () => `aktarın`],
  [/cut/i, () => `kesin`],
  [/slice/i, () => `dilimleyin`],
  [/dice/i, () => `küp doğrayın`],
  [/chop/i, () => `doğrayın`],
  [/mince/i, () => `kıyın`],
  [/grate/i, () => `rendeleyin`],
  [/peel/i, () => `soyun`],
  [/wash/i, () => `yıkayın`],
  [/drain/i, () => `süzün`],
  [/rinse/i, () => `çıkarın`],
  [/measure/i, () => `ölçün`],
  [/weigh/i, () => `tartın`],
  [/prepare/i, () => `hazırlayın`],
  [/mix/i, () => `karıştırın`],
  [/whisk/i, () => `çırpın`],
  [/beat/i, () => `çırpın`],
  [/blend/i, () => `karıştırın`],
  [/puree/i, () => `püre yapın`],
  [/grind/i, () => `çekin`],
  [/crush/i, () => `ezin`],
  [/squeeze/i, () => `sıkın`],
  [/pour/i, () => `dökün`],
  [/spoon/i, () => `kaşıkla alın`],
  [/arrange/i, () => `düzenleyin`],
  [/fill/i, () => `doldurun`],
  [/wrap/i, () => `sarın`],
  [/roll/i, () => `rulo yapın`],
  [/knead/i, () => `yoğurun`],
  [/shape/i, () => `şekil verin`],
  [/form/i, () => `şekil verin`],
  [/press/i, () => `bastırın`],
  [/flatten/i, () => `düzleştirin`],
  [/brush/i, () => `fırçalayın`],
  [/spread/i, () => `sürün`],
  [/layer/i, () => `katlayın`],
  [/repeat/i, () => `tekrarlayın`],
  [/continue/i, () => `devam edin`],
  [/finish/i, () => `bitirin`],
  [/enjoy/i, () => `afiyet olsun`],
];

function translateIngredient(ing) {
  const lower = ing.toLowerCase();
  for (const [en, tr] of Object.entries(ingredientDict)) {
    if (lower.includes(en)) {
      return lower.replace(new RegExp(en, "gi"), tr);
    }
  }
  return ing;
}

function translateStep(step) {
  for (const [pattern, replacer] of stepPatterns) {
    const m = step.match(pattern);
    if (m) {
      return replacer(m, ...m.slice(1));
    }
  }
  return step;
}

function translateName(name) {
  const lower = name.toLowerCase();
  for (const [en, tr] of Object.entries(ingredientDict)) {
    if (lower.includes(en)) {
      return lower.replace(new RegExp(en, "gi"), tr);
    }
  }
  return name;
}

const files = fs.readdirSync(dir).filter((f) => f.endsWith(".ts") && f !== "index.ts");

for (const file of files) {
  const filePath = path.join(dir, file);
  let content = fs.readFileSync(filePath, "utf8");

  content = content.replace(
    /"name":\s*\{\s*"tr":\s*"([^"]+)",\s*"en":\s*"([^"]+)"\s*\}/g,
    (_, tr, en) => {
      const trName = translateName(tr);
      return `"name": { "tr": "${trName}", "en": "${en}" }`;
    }
  );

  content = content.replace(
    /"ingredients":\s*\[([\s\S]*?)\]/g,
    (_, ingredientsStr) => {
      const ingredients = ingredientsStr.match(/"([^"]+)"/g) || [];
      const translated = ingredients.map((ing) => {
        const clean = ing.slice(1, -1);
        return `"${translateIngredient(clean)}"`;
      });
      return `"ingredients": [${translated.join(", ")}]`;
    }
  );

  content = content.replace(
    /"steps":\s*\{\s*"tr":\s*\[([\s\S]*?)\],\s*"en":\s*\[([\s\S]*?)\]\s*\}/g,
    (_, trStepsStr, enStepsStr) => {
      const trSteps = trStepsStr.match(/"([^"]+)"/g) || [];
      const enSteps = enStepsStr.match(/"([^"]+)"/g) || [];
      const translatedTr = trSteps.map((s) => {
        const clean = s.slice(1, -1);
        return `"${translateStep(clean)}"`;
      });
      const translatedEn = enSteps.map((s) => {
        const clean = s.slice(1, -1);
        return `"${clean}"`;
      });
      return `"steps": { "tr": [${translatedTr.join(", ")}], "en": [${translatedEn.join(", ")}] }`;
    }
  );

  fs.writeFileSync(filePath, content);
  console.log("Translated:", file);
}
console.log("Done!");
